// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlmrhnqgbktamxqdumzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsbXJobnFnYmt0YW14cWR1bXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNTU1NTQsImV4cCI6MjA3NTgzMTU1NH0.zcIeKRFulIor3H5aC2mzce-bNXJRRCjkIIDMCpAdXvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});